name: Android APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            platforms;android-35
            build-tools;35.0.0

      - name: Install Cordova
        run: npm i -g cordova

      - name: Prepare Android platform
        run: |
          cordova platform rm android || true
          cordova platform add android

      - name: Build debug APK
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        run: cordova build android --no-telemetry --no-update-notifier

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NoaApp-debug
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
