name: Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: true

      - name: Build debug APK with Cordova
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx2048m"
        run: |
          npm i -g cordova@12
          cordova telemetry off || true
          cordova platform rm android || true
          cordova platform add android
cat > .github/workflows/build-android.yml <<'YAML'
name: Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: true

      - name: Build debug APK with Cordova
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx2048m"
        run: |
          npm i -g cordova@12
          cordova telemetry off || true
          cordova platform rm android || true
          cordova platform add android@13

cordova build android --debug --no-telemetry --no-update-notifier

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NoaApp-debug
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
